include: package:lint/analysis_options_package.yaml

linter:
  rules:
    # Use parameter order as in json response
    always_put_required_named_parameters_first: false

    # Util classes are awesome!
    avoid_classes_with_only_static_members: false

    # The new tabs vs. spaces. Choose wisely
    prefer_single_quotes: true

    # Good packages document everything
    public_member_api_docs: true

    # Blindly follow the Flutter code style, which prefers types everywhere
    always_specify_types: true
