name: contributors_ui
description: A Flutter package for showing contributors of a project on GitHub in a nice UI.
version: 0.0.1
author: Yazeed AlKhalaf <yazeedfady@gmail.com>
homepage: https://github.com/YazeedAlKhalaf/contributors_ui

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  stacked: ^1.9.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
